export const appRoutesKeys = [
  //PARENT ROUTES
  "dashboard",
  "notification",
  "farmers",
  "crops",
  "income-exp",
  "users",
  "reports",
  "settings",
  //CHILDREN ROUTES
  "audit-trails",
  "sms-messages",
  "manage-farmer",
  "farmland-details",
  "crops-yields",
  "farm-activity",
  "expenditure",
  "income",
  "insurance-claims",
  "loans",
  "employees",
  "manage-users",
  "user-logs",
  "crops-report",
  "farmers-report",
  "employees-report",
  "financial-report",
  "farmland-report",
  "weather-report",
  "system-params",
  "access-control",
  "manage-categories",
  //OTHER ROUTES
  "profile",
];



// FARMERS DATA
export const farmersTableHeading = [
  "Farmer ID",
  "First Name",
  "Last Name",
  "Surname",
  "Gender",
  "Date of Birth",
  "Marital Status",
  "National ID",
  "Contact Details",
  "Residential Address",
  "Region",
  "District",
  "Community/Village",
  "Educational Level",
  "Farm Location",
  "Farm GPS Coordinates",
  "Land Size",
  "Land Ownership",
  "Farming Practice",
  "Crop Type",
  "Livestock Type",
  "Harvest Dates",
  "Farming Experience",
  "Mechanization",
  "Soil Type",
  "Revenue",
  "Market Prices",
  "Yield Per Acre",
  "Smartphone Ownership",
  "Internet Access",
  "Digital Platform Use",
  "USSD/SMS Familiarity",
  "Date Created",
  "Active Status"
];


//Farmer necessary fields
export const farmerKeys = [
  "id",
   null,
  "first_name",
  "last_name",
  "surname",
  "gender",
  "date_of_birth",
  "marital_status",
  "national_id",
  "contact_details",
  "residential_address",
  "region",
  "district",
  "community_or_village",
  "educational_level",
  "farm_location",
  "farm_gps_coordinate",
  "land_size",
  "land_ownership",
  "farming_practice",
  "crop_type",
  "livestock_type",
  "harvest_dates",
  "farming_experience",
  "mechanization",
  "soil_type",
  "revenue",
  "market_prices",
  "yield_per_acre",
  "smartphone_ownership",
  "internet_access",
  "digital_platform_use",
  "ussd_sms_familiarity",
  "date_created",
];
